export const colorPalettes = {
  default: {
    backgroundGradientStart: '#E6F0FA',
    backgroundGradientEnd: '#D6E6F2',
    appBarBackground: 'rgba(26, 37, 47, 0.8)',
    text: '#2C3E50',
    textSecondary: '#7F8C8D',
    textHint: '#95A5A6',
    primary: '#3498DB',
    primaryDark: '#2980B9',
    secondary: '#F1C40F',
    icon: '#3498DB',
    buttonText: '#ffffff',
    divider: 'rgba(0, 0, 0, 0.1)',
    cardBackground: '#ffffff',
    cardDetailBackground: '#F8F9FA',
    error: '#E74C3C',
    success: '#2ECC71',
    errorButtonHover: '#C0392B',
    successButtonHover: '#27AE60',
  },
  palette1: {
    backgroundGradientStart: '#F7CFD8',
    backgroundGradientEnd: '#F4F8D3',
    appBarBackground: '#A6D6D6',
    text: '#8E7DBE',
    textSecondary: '#A6D6D6',
    textHint: '#F4F8D3',
    primary: '#8E7DBE',
    primaryDark: '#7A6AA6',
    secondary: '#F7CFD8',
    icon: '#8E7DBE',
    buttonText: '#ffffff',
    divider: 'rgba(0, 0, 0, 0.1)',
    cardBackground: '#F4F8D3',
    cardDetailBackground: '#F7CFD8',
    error: '#FF6B6B',
    success: '#2ECC71',
    errorButtonHover: '#E65A5A',
    successButtonHover: '#27AE60',
  },
  palette2: {
    backgroundGradientStart: '#3A59D1',
    backgroundGradientEnd: '#7AC6D2',
    appBarBackground: '#B5FCCD',
    text: '#3D90D7',
    textSecondary: '#7AC6D2',
    textHint: '#B5FCCD',
    primary: '#3A59D1',
    primaryDark: '#2E47A8',
    secondary: '#7AC6D2',
    icon: '#3A59D1',
    buttonText: '#ffffff',
    divider: 'rgba(0, 0, 0, 0.1)',
    cardBackground: '#B5FCCD',
    cardDetailBackground: '#7AC6D2',
    error: '#FF6B6B',
    success: '#2ECC71',
    errorButtonHover: '#E65A5A',
    successButtonHover: '#27AE60',
  },
  palette3: {
    backgroundGradientStart: '#0118D8',
    backgroundGradientEnd: '#E9DFC3',
    appBarBackground: '#FFF8F8',
    text: '#1B56FD',
    textSecondary: '#E9DFC3',
    textHint: '#FFF8F8',
    primary: '#1B56FD',
    primaryDark: '#1544CA',
    secondary: '#E9DFC3',
    icon: '#1B56FD',
    buttonText: '#ffffff',
    divider: 'rgba(0, 0, 0, 0.1)',
    cardBackground: '#FFF8F8',
    cardDetailBackground: '#E9DFC3',
    error: '#FF6B6B',
    success: '#2ECC71',
    errorButtonHover: '#E65A5A',
    successButtonHover: '#27AE60',
  },
  palette4: {
    backgroundGradientStart: '#FFBE98',
    backgroundGradientEnd: '#F05A7E',
    appBarBackground: '#0B8494',
    text: '#125B9A',
    textSecondary: '#F05A7E',
    textHint: '#FFBE98',
    primary: '#125B9A',
    primaryDark: '#0E4878',
    secondary: '#F05A7E',
    icon: '#125B9A',
    buttonText: '#ffffff',
    divider: 'rgba(0, 0, 0, 0.1)',
    cardBackground: '#0B8494',
    cardDetailBackground: '#FFBE98',
    error: '#FF6B6B',
    success: '#2ECC71',
    errorButtonHover: '#E65A5A',
    successButtonHover: '#27AE60',
  },
  palette5: {
    backgroundGradientStart: '#FF407D',
    backgroundGradientEnd: '#FFC4D4',
    appBarBackground: '#1B3C73',
    text: '#40679E',
    textSecondary: '#FFC4D4',
    textHint: '#FF407D',
    primary: '#40679E',
    primaryDark: '#33557F',
    secondary: '#FF407D',
    icon: '#40679E',
    buttonText: '#ffffff',
    divider: 'rgba(0, 0, 0, 0.1)',
    cardBackground: '#1B3C73',
    cardDetailBackground: '#FFC4D4',
    error: '#FF6B6B',
    success: '#2ECC71',
    errorButtonHover: '#E65A5A',
    successButtonHover: '#27AE60',
  },
};